<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PedidoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pedidos')->insert([
            [
                'data_transacao' => Carbon::parse('01-12-2024')->format('Y-m-d'),
                'cliente_id' => 1,
                'endereco_id' => 1,
                'status_id' => 4,
                'forma_pagamento_id' => 1,
                'valor_total' => 520.00,
                'desconto_total' => 52.00,
                'valor_frete' => 15.95,
                'valor_final' => 483.95,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('02-12-2024')->format('Y-m-d'),
                'cliente_id' => 2,
                'endereco_id' => 2,
                'status_id' => 2,
                'forma_pagamento_id' => 3,
                'valor_total' => 900.00,
                'desconto_total' => null,
                'valor_frete' => 20.4,
                'valor_final' => 920.40,
                'parcelas' => 6,
            ],
            [
                'data_transacao' => Carbon::parse('03-12-2024')->format('Y-m-d'),
                'cliente_id' => 3,
                'endereco_id' => 3,
                'status_id' => 6,
                'forma_pagamento_id' => 2,
                'valor_total' => 1600.00,
                'desconto_total' => null,
                'valor_frete' => 18.6,
                'valor_final' => 1618.60,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('04-12-2024')->format('Y-m-d'),
                'cliente_id' => 1,
                'endereco_id' => 1,
                'status_id' => 3,
                'forma_pagamento_id' => 3,
                'valor_total' => 6400.00,
                'desconto_total' => null,
                'valor_frete' => 15.95,
                'valor_final' => 6415.95,
                'parcelas' => 8,
            ],
            [
                'data_transacao' => Carbon::parse('05-12-2024')->format('Y-m-d'),
                'cliente_id' => 2,
                'endereco_id' => 2,
                'status_id' => 5,
                'forma_pagamento_id' => 1,
                'valor_total' => 640.00,
                'desconto_total' => 64.00,
                'valor_frete' => 20.40,
                'valor_final' => 596.40,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('06-12-2024')->format('Y-m-d'),
                'cliente_id' => 3,
                'endereco_id' => 3,
                'status_id' => 1,
                'forma_pagamento_id' => 2,
                'valor_total' => 600.00,
                'desconto_total' => null,
                'valor_frete' => 18.60,
                'valor_final' => 618.60,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('07-12-2024')->format('Y-m-d'),
                'cliente_id' => 1,
                'endereco_id' => 1,
                'status_id' => 7,
                'forma_pagamento_id' => 3,
                'valor_total' => 900.00,
                'desconto_total' => null,
                'valor_frete' => 15.95,
                'valor_final' => 915.95,
                'parcelas' => 4,
            ],
            [
                'data_transacao' => Carbon::parse('08-12-2024')->format('Y-m-d'),
                'cliente_id' => 2,
                'endereco_id' => 2,
                'status_id' => 8,
                'forma_pagamento_id' => 1,
                'valor_total' => 800.00,
                'desconto_total' => 80.00,
                'valor_frete' => 20.4,
                'valor_final' => 740.40,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('09-12-2024')->format('Y-m-d'),
                'cliente_id' => 3,
                'endereco_id' => 3,
                'status_id' => 9,
                'forma_pagamento_id' => 3,
                'valor_total' => 1500.00,
                'desconto_total' => null,
                'valor_frete' => 18.6,
                'valor_final' => 1518.60,
                'parcelas' => 10,
            ],
            [
                'data_transacao' => Carbon::parse('10-12-2024')->format('Y-m-d'),
                'cliente_id' => 1,
                'endereco_id' => 1,
                'status_id' => 4,
                'forma_pagamento_id' => 2,
                'valor_total' => 2400.00,
                'desconto_total' => null,
                'valor_frete' => 15.95,
                'valor_final' => 2415.95,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('11-12-2024')->format('Y-m-d'),
                'cliente_id' => 2,
                'endereco_id' => 2,
                'status_id' => 1,
                'forma_pagamento_id' => 3,
                'valor_total' => 400.00,
                'desconto_total' => null,
                'valor_frete' => 20.4,
                'valor_final' => 420.40,
                'parcelas' => 7,
            ],
            [
                'data_transacao' => Carbon::parse('12-12-2024')->format('Y-m-d'),
                'cliente_id' => 3,
                'endereco_id' => 3,
                'status_id' => 5,
                'forma_pagamento_id' => 1,
                'valor_total' => 1350.00,
                'desconto_total' => 135.00,
                'valor_frete' => 18.60,
                'valor_final' => 1233.60,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('13-12-2024')->format('Y-m-d'),
                'cliente_id' => 1,
                'endereco_id' => 1,
                'status_id' => 9,
                'forma_pagamento_id' => 2,
                'valor_total' => 320.00,
                'desconto_total' => null,
                'valor_frete' => 15.95,
                'valor_final' => 335.95,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('14-12-2024')->format('Y-m-d'),
                'cliente_id' => 2,
                'endereco_id' => 2,
                'status_id' => 6,
                'forma_pagamento_id' => 1,
                'valor_total' => 280.00,
                'desconto_total' => 28.00,
                'valor_frete' => 20.40,
                'valor_final' => 272.40,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('15-12-2024')->format('Y-m-d'),
                'cliente_id' => 3,
                'endereco_id' => 3,
                'status_id' => 3,
                'forma_pagamento_id' => 3,
                'valor_total' => 450.00,
                'desconto_total' => null,
                'valor_frete' => 18.6,
                'valor_final' => 468.60,
                'parcelas' => 5,
            ],
        ]);
    }
}
