<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PedidoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pedidos')->insert([
            [
                'data_transacao' => Carbon::parse('01-12-2024')->format('Y-m-d'),
                'cliente_id' => 1,
                'endereco_id' => 1,
                'status_id' => 4,
                'forma_pagamento_id' => 1,
                'valor_total' => 1500.00,
                'desconto_total' => 150.00,
                'valor_final' => 1350.00,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('02-12-2024')->format('Y-m-d'),
                'cliente_id' => 2,
                'endereco_id' => 2,
                'status_id' => 2,
                'forma_pagamento_id' => 3,
                'valor_total' => 3000.00,
                'desconto_total' => null,
                'valor_final' => 3000.00,
                'parcelas' => 6,
            ],
            [
                'data_transacao' => Carbon::parse('03-12-2024')->format('Y-m-d'),
                'cliente_id' => 3,
                'endereco_id' => 3,
                'status_id' => 6,
                'forma_pagamento_id' => 2,
                'valor_total' => 1200.00,
                'desconto_total' => null,
                'valor_final' => 1200.00,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('04-12-2024')->format('Y-m-d'),
                'cliente_id' => 1,
                'endereco_id' => 1,
                'status_id' => 3,
                'forma_pagamento_id' => 3,
                'valor_total' => 2500.00,
                'desconto_total' => null,
                'valor_final' => 2500.00,
                'parcelas' => 8,
            ],
            [
                'data_transacao' => Carbon::parse('05-12-2024')->format('Y-m-d'),
                'cliente_id' => 2,
                'endereco_id' => 2,
                'status_id' => 5,
                'forma_pagamento_id' => 1,
                'valor_total' => 1750.00,
                'desconto_total' => 175.00,
                'valor_final' => 1575.00,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('06-12-2024')->format('Y-m-d'),
                'cliente_id' => 3,
                'endereco_id' => 3,
                'status_id' => 1,
                'forma_pagamento_id' => 2,
                'valor_total' => 800.00,
                'desconto_total' => null,
                'valor_final' => 800.00,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('07-12-2024')->format('Y-m-d'),
                'cliente_id' => 1,
                'endereco_id' => 1,
                'status_id' => 7,
                'forma_pagamento_id' => 3,
                'valor_total' => 3200.00,
                'desconto_total' => null,
                'valor_final' => 3200.00,
                'parcelas' => 4,
            ],
            [
                'data_transacao' => Carbon::parse('08-12-2024')->format('Y-m-d'),
                'cliente_id' => 2,
                'endereco_id' => 2,
                'status_id' => 8,
                'forma_pagamento_id' => 1,
                'valor_total' => 1500.00,
                'desconto_total' => 150.00,
                'valor_final' => 1350.00,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('09-12-2024')->format('Y-m-d'),
                'cliente_id' => 3,
                'endereco_id' => 3,
                'status_id' => 9,
                'forma_pagamento_id' => 3,
                'valor_total' => 6000.00,
                'desconto_total' => null,
                'valor_final' => 6000.00,
                'parcelas' => 10,
            ],
            [
                'data_transacao' => Carbon::parse('10-12-2024')->format('Y-m-d'),
                'cliente_id' => 1,
                'endereco_id' => 1,
                'status_id' => 4,
                'forma_pagamento_id' => 2,
                'valor_total' => 2200.00,
                'desconto_total' => null,
                'valor_final' => 2200.00,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('11-12-2024')->format('Y-m-d'),
                'cliente_id' => 2,
                'endereco_id' => 2,
                'status_id' => 1,
                'forma_pagamento_id' => 3,
                'valor_total' => 3500.00,
                'desconto_total' => null,
                'valor_final' => 3500.00,
                'parcelas' => 7,
            ],
            [
                'data_transacao' => Carbon::parse('12-12-2024')->format('Y-m-d'),
                'cliente_id' => 3,
                'endereco_id' => 3,
                'status_id' => 5,
                'forma_pagamento_id' => 1,
                'valor_total' => 2700.00,
                'desconto_total' => 270.00,
                'valor_final' => 2430.00,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('13-12-2024')->format('Y-m-d'),
                'cliente_id' => 1,
                'endereco_id' => 1,
                'status_id' => 9,
                'forma_pagamento_id' => 2,
                'valor_total' => 1000.00,
                'desconto_total' => null,
                'valor_final' => 1000.00,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('14-12-2024')->format('Y-m-d'),
                'cliente_id' => 2,
                'endereco_id' => 2,
                'status_id' => 6,
                'forma_pagamento_id' => 1,
                'valor_total' => 1250.00,
                'desconto_total' => 125.00,
                'valor_final' => 1125.00,
                'parcelas' => null,
            ],
            [
                'data_transacao' => Carbon::parse('15-12-2024')->format('Y-m-d'),
                'cliente_id' => 3,
                'endereco_id' => 3,
                'status_id' => 3,
                'forma_pagamento_id' => 3,
                'valor_total' => 4500.00,
                'desconto_total' => null,
                'valor_final' => 4500.00,
                'parcelas' => 5,
            ],
        ]);
    }
}
