services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql_codifica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - codifica

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_codifica
    restart: always
    environment:
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - codifica

  webserver:
    image: nginx:alpine
    container_name: nginx_codifica
    restart: always
    working_dir: /var/www/html
    volumes:
      - ".:/var/www/html"
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/laravel.conf:/etc/nginx/conf.d/laravel.conf"
    ports:
      - "80:80"
    networks:
      - codifica

  php-fpm:
    build: docker/php-fpm
    container_name: php_codifica
    restart: always
    working_dir: /var/www/html/
    volumes:
      - ".:/var/www/html"
      - "./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini"
    networks:
      - codifica

volumes:
  mysql-volume:
    driver: local

networks:
  codifica:
    driver: bridge
